# Generated by Django 5.0.3 on 2024-03-16 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=480)),
                ('country', models.CharField(max_length=1280)),
                ('region', models.CharField(blank=True, max_length=1280, null=True)),
                ('locality', models.CharField(max_length=1280)),
                ('street', models.CharField(max_length=1280)),
                ('house', models.CharField(max_length=160)),
                ('zip_code', models.CharField(max_length=160)),
                ('extra_data', models.CharField(blank=True, max_length=40960, null=True)),
                ('init_vector', models.CharField(max_length=160)),
                ('status', models.PositiveIntegerField(default=0)),
                ('change_status_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
