# Generated by Django 5.0.3 on 2024-03-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='reset_key',
            field=models.CharField(max_length=64),
        ),
    ]
