# Generated by Django 5.0.3 on 2024-03-18 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_resetpassword_reset_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
