version: '3.8'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - static_volume:/var/www/safevault/static
            - media_volume:/var/www/safevault/media
        ports:
            - 8000:8000
        env_file:
            - ./configs/config.env

volumes:
    static_volume:
    media_volume: