# Generated by Django 5.0.3 on 2024-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_data',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_photo',
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(default=0, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='expiration_date',
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='issue_date',
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='issuing_authority',
            field=models.CharField(default=0, max_length=2560),
            preserve_default=False,
        ),
    ]
