# Generated by Django 5.0.3 on 2024-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_document_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=2560, null=True),
        ),
    ]
