# Generated by Django 5.0.3 on 2024-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.CharField(blank=True, max_length=1280, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='extra_data',
            field=models.CharField(blank=True, max_length=40960, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='website',
            field=models.CharField(blank=True, max_length=2560, null=True),
        ),
    ]
